<?php

namespace Gestor\MensajeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MensajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeRepository extends EntityRepository
{
    
    public function findMensajesUsuario($usuario){
        
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
                select m
                from MensajeBundle:Mensaje m
                where m.fkusuario = :usuario
            ');
        $consulta->setParameter('usuario', $usuario);
        
        return $consulta->getResult();
        
    }
    
    public function altaMensaje($mensaje){
        
        $em = $this->getEntityManager();
        $em->persist($mensaje);
        $em->flush();
    }
}
