<?php

namespace Gestor\MaterialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MaterialPolicialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialPolicialRepository extends EntityRepository
{
    
    public function altaMaterialPolicial($data,$expediente){
        
        $materialPolicial = new MaterialPolicial();
        
        $materialPolicial->asignarDatos(
                $expediente,
                $data->getDescripcion(),
                $data->getTipo(),
                $data->getMarca(),
                $data->getModelo(),
                $data->getTalla(),
                $data->getNumSerie(),
                $data->getDestino(),
                $data->getCantidad(),
                $data->getObservaciones());
        
        $em = $this->getEntityManager();
        $em->persist($materialPolicial);
        $em->flush();
        
        return $materialPolicial;
    }
}
